# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c://design/calculator.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(572, 489)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.BUTTONPLUS = QtWidgets.QPushButton(self.centralwidget)
        self.BUTTONPLUS.setObjectName("BUTTONPLUS")
        self.gridLayout.addWidget(self.BUTTONPLUS, 5, 3, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 4, 3, 1, 1)
        self.BUTTONSIX = QtWidgets.QPushButton(self.centralwidget)
        self.BUTTONSIX.setObjectName("BUTTONSIX")
        self.gridLayout.addWidget(self.BUTTONSIX, 2, 1, 1, 1)
        self.BUTTONEGHT = QtWidgets.QPushButton(self.centralwidget)
        self.BUTTONEGHT.setObjectName("BUTTONEGHT")
        self.gridLayout.addWidget(self.BUTTONEGHT, 2, 2, 1, 1)
        self.BUTTONAC = QtWidgets.QPushButton(self.centralwidget)
        self.BUTTONAC.setObjectName("BUTTONAC")
        self.gridLayout.addWidget(self.BUTTONAC, 2, 0, 1, 1)
        self.BUTTONNINE = QtWidgets.QPushButton(self.centralwidget)
        self.BUTTONNINE.setText("")
        self.BUTTONNINE.setObjectName("BUTTONNINE")
        self.gridLayout.addWidget(self.BUTTONNINE, 2, 3, 1, 1)
        self.BUTTONZERO = QtWidgets.QPushButton(self.centralwidget)
        self.BUTTONZERO.setObjectName("BUTTONZERO")
        self.gridLayout.addWidget(self.BUTTONZERO, 3, 3, 1, 1)
        self.BUTTONZAPYATAYA = QtWidgets.QPushButton(self.centralwidget)
        self.BUTTONZAPYATAYA.setObjectName("BUTTONZAPYATAYA")
        self.gridLayout.addWidget(self.BUTTONZAPYATAYA, 3, 2, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 3, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 3, 0, 1, 1)
        self.BUTTONMINUC = QtWidgets.QPushButton(self.centralwidget)
        self.BUTTONMINUC.setObjectName("BUTTONMINUC")
        self.gridLayout.addWidget(self.BUTTONMINUC, 6, 3, 1, 1)
        self.BUTTONUMNOJIT = QtWidgets.QPushButton(self.centralwidget)
        self.BUTTONUMNOJIT.setObjectName("BUTTONUMNOJIT")
        self.gridLayout.addWidget(self.BUTTONUMNOJIT, 4, 2, 1, 1)
        self.BUTTONDELIT = QtWidgets.QPushButton(self.centralwidget)
        self.BUTTONDELIT.setObjectName("BUTTONDELIT")
        self.gridLayout.addWidget(self.BUTTONDELIT, 5, 2, 1, 1)
        self.BUTTONRAVNO = QtWidgets.QPushButton(self.centralwidget)
        self.BUTTONRAVNO.setText("")
        self.BUTTONRAVNO.setObjectName("BUTTONRAVNO")
        self.gridLayout.addWidget(self.BUTTONRAVNO, 6, 2, 1, 1)
        self.BUTTONONE = QtWidgets.QPushButton(self.centralwidget)
        self.BUTTONONE.setObjectName("BUTTONONE")
        self.gridLayout.addWidget(self.BUTTONONE, 4, 1, 1, 1)
        self.BUTTONTWO = QtWidgets.QPushButton(self.centralwidget)
        self.BUTTONTWO.setObjectName("BUTTONTWO")
        self.gridLayout.addWidget(self.BUTTONTWO, 5, 1, 1, 1)
        self.BUTTONTREE = QtWidgets.QPushButton(self.centralwidget)
        self.BUTTONTREE.setObjectName("BUTTONTREE")
        self.gridLayout.addWidget(self.BUTTONTREE, 6, 1, 1, 1)
        self.BUTTONFOUR = QtWidgets.QPushButton(self.centralwidget)
        self.BUTTONFOUR.setObjectName("BUTTONFOUR")
        self.gridLayout.addWidget(self.BUTTONFOUR, 4, 0, 1, 1)
        self.BUTTONFIVE = QtWidgets.QPushButton(self.centralwidget)
        self.BUTTONFIVE.setObjectName("BUTTONFIVE")
        self.gridLayout.addWidget(self.BUTTONFIVE, 5, 0, 1, 1)
        self.BUTTONSEVEN = QtWidgets.QPushButton(self.centralwidget)
        self.BUTTONSEVEN.setObjectName("BUTTONSEVEN")
        self.gridLayout.addWidget(self.BUTTONSEVEN, 6, 0, 1, 1)
        self.OTVET = QtWidgets.QLabel(self.centralwidget)
        self.OTVET.setObjectName("OTVET")
        self.gridLayout.addWidget(self.OTVET, 1, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 572, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.BUTTONPLUS.setText(_translate("MainWindow", "+"))
        self.pushButton_9.setText(_translate("MainWindow", "-"))
        self.BUTTONSIX.setText(_translate("MainWindow", "/"))
        self.BUTTONEGHT.setText(_translate("MainWindow", "*"))
        self.BUTTONAC.setText(_translate("MainWindow", "AC"))
        self.BUTTONZERO.setText(_translate("MainWindow", "+/-"))
        self.BUTTONZAPYATAYA.setText(_translate("MainWindow", "9"))
        self.pushButton_7.setText(_translate("MainWindow", "8"))
        self.pushButton_8.setText(_translate("MainWindow", "7"))
        self.BUTTONMINUC.setText(_translate("MainWindow", "="))
        self.BUTTONUMNOJIT.setText(_translate("MainWindow", "6"))
        self.BUTTONDELIT.setText(_translate("MainWindow", "3"))
        self.BUTTONONE.setText(_translate("MainWindow", "5"))
        self.BUTTONTWO.setText(_translate("MainWindow", "2"))
        self.BUTTONTREE.setText(_translate("MainWindow", ","))
        self.BUTTONFOUR.setText(_translate("MainWindow", "4"))
        self.BUTTONFIVE.setText(_translate("MainWindow", "1"))
        self.BUTTONSEVEN.setText(_translate("MainWindow", "0"))
        self.OTVET.setText(_translate("MainWindow", "TextLabel"))

